spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    # 多环境开发
    active: dev
  banner:
    # banner路径
    location: classpath:static/banner.txt
  # 设置reid配置
  redis:
    timeout: 1800000
    host: 192.168.187.129
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
    password: 123123
  # 设置最大文件大小multipartFile
  servlet:
    multipart:
      max-file-size: 10MB