# 开发环境
spring:
  # swagger 配置
  swagger:
    enabled: true
    title: '后台API接口开发文档'
    description: 'API开发文档'
    version: 1.4.1
    contact:
      name: 'Mnsx_x'
      url: 'https://github.com/Mnsx'
      email: 'xx1527030652@gmail.com'

  # 数据库配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost/xhk?serverTimeZone=Asia/Shanghai
      username: root
      password: 123123

server:
  port: 8081