server:
  port: 80
  servlet:
    context-path: /xhk
  #tomcat:
    #remoteip:
      #host-header: x-forwarded-for
      #protocol-header: x-forwarded-proto
      #port-header: X-Forwarded-Port
  #forward-headers-strategy: native

spring:
  banner:
    location: classpath:/static/banner.txt
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xhk?userUnicode=true&userSSL=false&characterEncoding=UTF-8&serverTimeZone=GMT%2B8
      username: root
      password: 123123
  mvc:
    view:
      prefix: /xhk
mybatis-plus:
  global-config:
    db-config:
      table-prefix: xhk_
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
